# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f82d760821631a4990a1c5ff3c4cd793"
name = "Ecommerce"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "unauthenticated_read_product_listings,unauthenticated_read_checkouts,unauthenticated_write_checkouts,unauthenticated_read_customers,unauthenticated_write_customers,unauthenticated_read_customer_tags,unauthenticated_read_content,unauthenticated_read_metaobjects,unauthenticated_read_product_inventory,unauthenticated_read_product_pickup_locations,unauthenticated_read_product_tags,unauthenticated_read_selling_plans"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
